const ROUTES = {
  HOME: "/",
  REGISTER: "/register",
  LOGIN: "/login",
  EDITCARD: "/editcard",
  CREATECARD: "/CreateCardPage",
  SANDBOX: "/sandboxPage",
  ABOUT: "/About",
  FAVCARD: "/favoriteCardPage",
  MYCARDS: "/MyCardsPage",
  EDITSTATUS: "/EditStatusPage",
  EDITCARDPAGE: "/EditCardPage",
  EDITPROFILE: "/EditProfile",
  CARDDETAILS: "/CardDetailsPage",
  CARTPAGE: "/CartPage",
  CHECKOUTPAGE: "/Chekcoutpage",
  THANKYOUPAGE: "/ThankYouPage",
  CARDINFORMATIONPAGE: "/CardInformationPage",
  VERIFICATIONPAGE: "/VerificationPage",
  FORGOTPASSWORD: "ForgotPassword",
  RESETPASSWORD: "/ResetPassword/:userId/:token",
  CONTACTME: "/ContactMe",
};
export default ROUTES;
